#sudo: false

language: cpp

compiler:
  - gcc
  - clang

dist: trusty
 
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
#   - boost-latest
#   - llvm-toolchain-precise-3.6
    packages:
#    - g++-4.8
    - g++-5
#    - libboost1.55-all-dev
    - valgrind
#    - clang-3.6
    - libicu52

install:
  # g++
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5"; fi
  
before_script: 
  # display cpu info
  - cat /proc/cpuinfo
  - $CXX --version
  - echo "CXX="$CXX
  - mkdir obj
  
script: 
  - make
  - ./DeepovTesting 
 # valgrind --leak-check=full --show-reachable=yes --track-origins=yes --error-exitcode=1  ./DeepovTesting exclude:perft
  - cd test/EloRegressionTest/
  - ./eloRegressionTest.sh

 
notifications:
  email:
    recipients:
      - navid.hedjazian@gmail.com
      - romain.goussault@gmail.com
