language: cpp

compiler:
  - gcc
  
before_install:
 # g++4.8.1
 - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
 - sudo apt-get update -qq

install:
  # g++4.8.1
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  
  # Boost
  - sudo apt-get install libboost-dev

  # Valgrind
  - sudo apt-get install valgrind
  
before_script:
  - $CXX --version
  - echo "CXX="$CXX
  - mkdir obj
  
script: 
  - make
  - ./DeepovTesting 
  - valgrind --leak-check=full --show-reachable=yes --error-exitcode=1  ./DeepovTesting
 
notifications:
  email:
    recipients:
      - navid.hedjazian@gmail.com
      - romain.goussault@gmail.com
